name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win32
            architecture: x86
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
          - os: ubuntu-latest
            artifact-name: Linux
            architecture: x64

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}
      - name: Import Developer ID Certificate
        uses: devbotsxyz/xcode-import-certificate@v1
        with:
          certificate-data: ${{ secrets.CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        if: ${{ matrix.artifact-name == 'macOS' }}
      - run: ./gradlew build -PbuildServer -PdeveloperID=${{ secrets.DEVELOPER_ID }}
        if: |
          !startsWith(github.refs, 'refs/tags/v')
        name: Build with Gradle
      - run: ./gradlew build -PbuildServer -PreleaseMode -PdeveloperID=${{ secrets.DEVELOPER_ID }}
        if: startsWith(github.refs, 'refs/tags/v')
        name: Build with Gradle (Release)
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  combine:
    name: "Combine"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/download-artifact@v2
        with:
          path: build/allOutputs
      - run: ./gradlew publish -PbuildServer -PprCombinePublish
        name: Combine
        if: |
          !startsWith(github.ref, 'refs/tags/v') &&
          github.ref != 'refs/heads/master'
      - run: ./gradlew publish -PbuildServer
        name: Combine (Master)
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
      - run: ./gradlew publish -PbuildServer -PreleaseMode
        name: Combine (Release)
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
      - uses: actions/upload-artifact@v2
        with:
          name: Maven
          path: ~/releases
